version: '3'

services:
  ui:
    image: 'node:10-alpine'
    working_dir: '/home/core-api/ui'
    volumes:
      - ./ui:/home/core-api/ui
    command: "sh -c 'npm install && npm start'"
    depends_on:
      - api
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
  api:
    image: 'node:10-alpine'
    working_dir: '/home/core-api/server'
    volumes:
      - ./server:/home/core-api/server
    command: "sh -c 'npm install && npm run dev'"
    depends_on:
      - db
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001

  db:
    image: 'mongo:4'